name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: macos-12
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print ending
        run: echo "Ok we are all done!"
